obj1 = Dlinkex.cpp Dlink.cpp Node.cpp
obj2 = main.cpp Queue.cpp Dlink.cpp Node.cpp
target1 = DlinkTest
target2 = QueueTest

${target1}: ${obj1}
	g++ -g ${obj1} -o ${target1}

${target2}: ${obj2}
	g++ -g ${obj2} -o ${target2}
